baseURL = "/"
languageCode = "pt-br"
title = "VC Sorrindo | Dr. Yohannes & Dra. Doraliza"
# Deixe o campo theme vazio para usarmos a nossa pasta layout pr√≥pria
theme = "" 

[params]
  whatsapp = "5534984105801"
  clinica = "VC Sorrindo"
  doutores = "Dr. Yohannes Verrone e Dra. Doraliza Cardoso"
