baseURL = "/"
languageCode = "pt-br"
title = "VC Sorrindo | Dr. Yohannes & Dra. Doraliza"
# N√ÉO coloque a linha theme aqui. O Hugo vai entender que deve usar a sua pasta 'layouts' direto.

[params]
  whatsapp = "5534984105801"
  clinica = "VC Sorrindo"
  doutores = "Dr. Yohannes Verrone e Dra. Doraliza Cardoso"
