baseURL = "/"
languageCode = "pt-br"
title = "VC Sorrindo | Dr. Yohannes & Dra. Doraliza"
theme = "ananke"

[params]
  whatsapp = "5534984105801"
  description = "Especialistas em Implantes e Saúde Bucal em Uberlândia."
