[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.0" # Define uma versão estável
  HUGO_ENABLEGITINFO = "true"

[context.production]
  environment = { HUGO_ENV = "production" }
